version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # use host IP for multiple brokers 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
  producer:
    build: ./data-processing-pipeline/producer
    depends_on:
      - kafka
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    links:
      - kafka:kafka

  consumer:
    build: ./data-processing-pipeline/consumer
    depends_on:
      - kafka
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    links:
      - kafka:kafka
