version: '3.5'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/sinoed/data/db:/data/db
    networks:
      - shared-net
    
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - shared-net
      
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # use host IP for multiple brokers 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "message:1:1"
    networks:
      - shared-net
      
  producer:
    build: ./data-processing-pipeline/producer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - kafka
    networks:
      - shared-net

  consumer:
    build: ./data-processing-pipeline/consumer
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - mongo
    links:
      - mongo
    networks:
      - shared-net
      
  client:
    container_name: client
    build: ./client
    volumes:
      - "./client:/usr/src/app" 
    ports: 
      - "4200:4200"
    depends_on:
      - producer
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
      
networks:
  shared-net:
    driver: bridge
